# This is a basic workflow to help you get started with Actions

name: Dynatrace Install

on: workflow_dispatch

env:
  zone: us-central1-c
  releaseName: dynatrace-oneagent-operator 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 Install-DT:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        #version: '290.0.1'
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    # Get new cluster credentials 
    - run: |-
        gcloud container clusters get-credentials ${{secrets.GKE_CLUSTER_NAME}} --zone=${{ env.zone }}
        kubectl create namespace dynatrace
    # Set up DT in Kubernetes cluster
    - run: |-
        helm repo add dynatrace https://raw.githubusercontent.com/Dynatrace/helm-charts/master/repos/stable
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
        helm install ${{ env.releaseName }} dynatrace/dynatrace-oneagent-operator -n dynatrace -f dynatrace/values.yaml --set secret.apiToken=${{ secrets.DYNATRACE_API_KEY }} --set secret.paasToken=${{ secrets.paasToken }} --set oneagent.apiUrl=${{ secrets.apiUrl }}
